### ISSUE TITLE
Build Rom

### ISSUE THREAD

**Issue by JStyle21** [thune-xiaobai/android_device_xiaomi_libra#8]
Hi,

I couldn't find a way to build your rom, what i did was sync the device to devices but since there is not kernel that is it.

Also i don't understand your `AndoridBoard.mk` it points to `kernel/xiaomi/libra/AndroidKernel.mk`
But there is no such file nor the kernel source, what am i missing?
I tried removing that line but it crashed on objects later in the build...

Can you please share some build instructions? what is did was:
`. build/envsetup.sh`
`lunch`
`make -j8 otapackage`

**Comment by thune-xiaobai** [comment]
xiaomi has not release it's kernel source yet,so i use a prebuilt-kernel.

This makefile is for qualcomm's HAL dependence.

see this for example:https://github.com/dianlujitao/android_kernel_zte_msm8994/tree/cm-12.1-pre

**Comment by JStyle21** [comment]
I am aware of the fact xiaomi is yet to release the sources, however what you are saying is that you have used a prebuilt-kernel of a different device? is so, doesn't it make more sense to use the same chipset at least? for example:
https://github.com/lg-devs/android_kernel_lge_msm8992

**Comment by thune-xiaobai** [comment]
No, it's not use a different device,but you need to create a similiar one use the kernel from xiaomi's official rom.

**Comment by JStyle21** [comment]
Sorry i don't understand.
Can you please explain some more? or refer to the right place?
You can just dump the boot partition from MIUI to a binary image which should get you the pre-built kernel for this device.
Why do you need the kernel mk file? if the drivers are already there what dependencies does the GPU require?

**Comment by thune-xiaobai** [comment]
mkdir boot && unpackbooimg -i boot.img -o boot
![qq 20160114191413](https://cloud.githubusercontent.com/assets/3123725/12323025/098a1134-baf3-11e5-8e58-426489be495a.png)

boot.img-dt is the dt.img and boot.img-zImage is the kernel.
kernel.mk is for some headers that were required by hardware/qcom
here I give you all the files you need：
link:http://pan.baidu.com/s/1nuzgoY1   password:bu2v

**Comment by Liberation-kkfire** [comment]
来看看,,,感谢小白哥的付出~~~学习中

**Comment by JStyle21** [comment]
Hi,
@thune-xiaobai 
I'm sorry to bother you about this but is it possible to upload the tar to a faster server?
The download speed of baidu is 3-5 kb/s which is ridicules...
How about a free service such as http://zippyshare.com/
